# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: MacOS Build

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-10.15

    env:
      CSC_IDENTITY_AUTO_DISCOVERY: false
      USE_HARD_LINKS: false

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: brew install boost mpv ninja

    - run: npm install
    - run: npm run collect:dylibs
    - run: npm run dist:mac
    # - run: npm test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: |
          dist/
          !dist/mac
          !dist/bundled
    - name: Download test Artifact
      uses: actions/upload-artifact@v2
      with:
        name: mochawesome-report # optional
        path: mochawesome-report/ # optional
